import tkinter as tk

class QnaPage:
    def __init__(self, container, root):
        self.container = container
        self.root = root
        
        # Professional Q&A Repository moved here
        #Questions generated by notebook.io after submitting the content of our applicaiton onto the content entry
        self.qnaData = [
            ("What is the goal of Pibbit?", "Pibbit aims to revitalize local economies by providing small businesses with a high-visibility digital platform."),
            ("How do I save a business for later?", "Logged-in users can click the 'Bookmark' button on any business card to save it to their personal collection."),
            ("Are the coupons verified?", "Yes, all coupons are managed directly by business owners through our secure database to ensure validity."),
            ("Can I use Pibbit without an account?", "You can explore businesses as a guest, but an account is required to rate, review, or access exclusive coupons."),
            ("How is my data protected?", "Pibbit uses secure database protocols to ensure user activity remains private and encrypted."),
            ("How do I export business info?", "Click the printer icon (🖨️) on any results page to generate a professional PDF report of the current business list."),
            ("Can I sort businesses by their reputation?", "Yes! Use the 'Highest Ratings' or 'Most Reviewed' buttons at the top of the search results to reorder the list."),
            ("How do I find businesses in a specific city?", "Click 'Select GA City' in the results toolbar to filter businesses by their specific Georgia location."),
            ("What happens if I forget my login?", "For security, Pibbit uses email-based authentication. Please contact the administrator to reset your credentials manually in the database."),
            ("How do I submit a review?", "Click 'Write a Review' on any business card. Your feedback helps the community make informed decisions."),
            ("How can a local business join Pibbit?", "Business owners can apply through our vendor portal. Once verified by an admin, their shop will appear in the directory."),
            ("Is the rating system weighted?", "Ratings are calculated as a simple average of all user submissions to provide the most transparent view of customer satisfaction.")
        ]

    def show(self):
        """Builds and displays the Q&A UI."""
        
        #Creating the scrollable Q&A List first
        self.qnaCanvas = tk.Canvas(self.container, bg="#BACAB8", highlightthickness=0)
        self.qnaScrollBar = tk.Scrollbar(self.container, orient="vertical", command=self.qnaCanvas.yview)
        self.qnaListContainer = tk.Frame(self.qnaCanvas, bg="#BACAB8")
        
        self.qnaCanvas.create_window((0, 0), window=self.qnaListContainer, anchor="nw", width=self.root.winfo_width()-100)
        self.qnaCanvas.configure(yscrollcommand=self.qnaScrollBar.set)

        self.qnaScrollBar.pack(side="right", fill="y")
        self.qnaCanvas.pack(side="bottom", fill="both", expand=True, padx=50)

        #Creating the search area
        searchBarFrame = tk.Frame(self.container, bg="#BACAB8", pady=20)
        searchBarFrame.pack(side="top", fill="x") # Pack this at the top

        tk.Label(searchBarFrame, text="How can we help you?", font=("Georgia", 24, "bold"), bg="#BACAB8").pack()
        
        self.searchBarVar = tk.StringVar()
        
        searchBarEntry = tk.Entry(searchBarFrame, textvariable=self.searchBarVar, font=("Georgia", 14), width=45, relief="flat", highlightthickness=1)
        searchBarEntry.pack(pady=10)
        searchBarEntry.insert(0, "Search for a question...")
        searchBarEntry.bind("<FocusIn>", lambda e: searchBarEntry.delete(0, 'end') if "Search for a question" in self.searchBarVar.get() else None)

        #Because qnaListContainer is  defined above, this won't crash!
        self.searchBarVar.trace_add("write", self.update_qa_results)
        self.update_qa_results()
    def update_qa_results(self, *args):
        if not hasattr(self, 'qnaListContainer'):
            return
        for widget in self.qnaListContainer.winfo_children():
            widget.destroy()

        query = self.searchBarVar.get().lower()
        if "search for a question" in query: query = ""

        found = False
        for q, a in self.qnaData:
            if query in q.lower() or query in a.lower():
                found = True
                f = tk.Frame(self.qnaListContainer, bg="#DDE0D6", bd=1, relief="solid", padx=15, pady=15)
                f.pack(fill="x", pady=5)
                tk.Label(f, text=f"Q: {q}", font=("Georgia", 13, "bold"), bg="#DDE0D6", fg="#2D5A27", anchor="w", justify="left").pack(fill="x")
                tk.Label(f, text=a, font=("Georgia", 11), bg="#DDE0D6", wraplength=800, justify="left", anchor="w").pack(fill="x", pady=(5,0))

        if not found:
            tk.Label(self.qnaListContainer, text="No matches found.", font=("Georgia", 12), bg="#BACAB8").pack(pady=20)

        self.qnaListContainer.update_idletasks()
        self.qnaCanvas.configure(scrollregion=self.qnaCanvas.bbox("all"))